---
- name: Install PHP packages
  sudo: yes
  apt:  package={{ item.package }} state=latest
  with_items: php_packages
  
- name: Set date.timezone apache
  sudo: yes
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^date.timezone" "line=Europe/Madrid"

- name: Set date.timezone cli
  sudo: yes
  lineinfile: dest=/etc/php5/cli/php.ini regexp="^date.timezone" "line=Europe/Madrid"
  notify: restart apache2
  
