---
- hosts: all
  sudo:  true
  vars:
    vhosts:
        - { server_name: uma.local, doc_root: /var/www/uma/web }
        - { server_name: sgr.local, doc_root: /var/www/sgr/web }            
    sys_packages:
      - mcrypt
      - postfix
      - acl
      - subversion
    apache2_packages:
        - { name: apache2, package: apache2 }
        - { name: mod_apache, package: libapache2-mod-php5 }
    php_packages:
      - { name: dev, package: php5-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: mysql, package: php5-cli }
      - { name: mysql, package: php5-json }
      - { name: mysql, package: php5-intl }
      - { name: mysql, package: php5-sqlite }
      - { name: apc, package: php-apc }
    symfony_apps:
      - { name: uma, path: /var/www/uma }
      - { name: sgr, path: /var/www/sgr }
    php_extensions:
      - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
      - { name: "mongo", package: "pecl.php.net/mongo" }
      - { name: "xhprof", package: "pecl.php.net/xhprof-beta" }
    php_ppa: php5
  roles:
    - init
    - apache2
    - mysql
    - php5
    - phpmyadmin
    - wget
    - curl
    - composer
    - phpunit  
    - git
    - sqlite
    - symfony_apps
#    - nginx
#    - php5-fpm
#    - php5-cli
#    - php5-common  
#    - mongo
#    - rabbitmq
