---    
  - name: Install phpMyAdmin
    sudo: yes
    action: apt pkg=phpmyadmin state=installed

  - name: Set up phpMyAdmin under Apache (/phpmyadmin)
    file: src=/etc/phpmyadmin/apache.conf dest=/etc/apache2/conf.d/phpmyadmin.conf state=link

  - name: Make phpmyadmin accessible without password (1st occurence)
    lineinfile: dest=/etc/phpmyadmin/config.inc.php regexp='\/\/(.*)AllowNoPassword(.*)' line='\1AllowNoPassword\2' backrefs=yes backup=yes

    # This is a bit of a hack. The line appears twice, only the first really needs to be changed,
    # but Ansible picks the last one on the first pass...
  - name: Make phpmyadmin accessible without password (2nd occurence)
    lineinfile: dest=/etc/phpmyadmin/config.inc.php regexp='\/\/(.*)AllowNoPassword(.*)' line='\1AllowNoPassword\2' backrefs=yes

